### ISSUE TITLE
I can't run the hello world

### ISSUE THREAD

**Issue by nicolaslecrique** [DiamondLovesYou/rust-pnacl-hello-world#1]
Hello,

I did not succeed in building/running the hello world. On the command "make SYSROOT=path/to/rust/build NACL_SDK=path/to/pepper serve", I get the error:

make: **\* No rule to make target `main.rs', needed by`/home/nico/dev/tests/pnacl_rust_hello_2/rust-pnacl-hello-world/build/pnacl-hello-world.stamp'

I run the command from the root directory of the repo

Maybe it's because there is a problem with dependencies, if I run the command "git submodule update --init" (as specified in the readme), nothing happens (the file .gitmodules is empty). with cargo build, some dependencies are loaded but I guess not in the layout expected by the Makefile.

I use pepper_37 and SYSROOT=//home/nico/dev/rust_pnacl/build/x86_64-unknown-linux-gnu/stage2 which is the build generated with your rust fork.

Thanks for your help

**Comment by DiamondLovesYou** [comment]
Oops, I had forgotten to commit and push some work. Sorry 'bout that!

**Comment by nicolaslecrique** [comment]
Hello,

Sorry, I still have some issues with your hello-world. I can't compile ppapi, here is the compilation error I get (I pulled/compiled everything yesterday) 

Thanks :-)

   Compiling ppapi v0.0.1 (https://github.com/DiamondLovesYou/rust-ppapi.git#3f5c3968)
src/lib/lib.rs:83:33: 83:47 warning: feature has been added to Rust, directive not necessary
src/lib/lib.rs:83 #![feature(default_type_params, struct_variant)]
                                                  ^~~~~~~~~~~~~~
src/lib/lib.rs:323:24: 323:40 error: unknown format trait `s`
src/lib/lib.rs:323                   code=self.to_string(), msg=msg)
                                          ^~~~~~~~~~~~~~~~
src/lib/lib.rs:323:46: 323:49 error: unknown format trait `s`
src/lib/lib.rs:323                   code=self.to_string(), msg=msg)
                                                                ^~~
src/lib/lib.rs:1466:1: 1466:15 error: macro undefined: 'local_data_key!'
src/lib/lib.rs:1466 local_data_key!(current_instance: Instance)
                    ^~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `ppapi`.

**Comment by DiamondLovesYou** [comment]
Related issue: https://github.com/DiamondLovesYou/rust-ppapi/issues/5. There are a large amount of changes that have to happen, mainly due to enum namespace changes, but I should have it all done sometime tonight (CST).

**Comment by DiamondLovesYou** [comment]
Oh, hey I forgot to update this issue. I've fixed/updated the plethora of compile errors in `rust-ppapi`.

I apologize for the delay in letting you know; I actually had this fixed a while ago.
